package day27_ExceptionHandeling_Part1;

public class ExceptionDemo4 {

    public static void main(String[] args) {
        try {

            try {

            } catch (Exception e) {

            }

        } catch (Exception e) {
            try {

            } catch (Exception ee) {

            }

        } finally {
            try {

            } catch (Exception e) {

            }

        }
    }
}
